[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "flaskteroids"
version = "0.1.1"
description = "Flask on steroids"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
  { name="Juan Sebastian Quintero" }
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Framework :: Flask",
]
dependencies = [
	"alembic>=1.15.1",
	"Flask",
	"python-dotenv>=1.0.1",
	"sqlalchemy",
	"celery"
]

[project.scripts]
flaskteroids = "flaskteroids.cli.flaskteroids:cli"


[tool.flake8]
max-line-length = 120

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
    "pytest-mock>=3.14.0",
    "ruff>=0.10.0",
]
